version: '2'

services:

  riot:
    #    image: allmende/riot:2017-06-19
    build: ./okfn-de-test-riot/
    restart: always
    command: start
    environment:
      VIRTUAL_HOST: okfn-de-test.riot.allmende.io
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: riot.allmende.io
      LETSENCRYPT_EMAIL: almeryda@allmende.io
    expose:
      - "8080"
    volumes:
      - /srv/okfn-de-test/data:/data
    networks:
      - frontend

  matrix:
    image: allmende/synapse:v0.21.1
    restart: always
    command: start
    environment:
      VIRTUAL_HOST: okfn-de-test.matrix.allmende.io
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: okfn-de-test.matrix.allmende.io
      LETSENCRYPT_EMAIL: almereyda@allmende.io
    expose:
      - "8080"
    volumes:
      - /srv/okfn-de-test/data:/data
      - /srv/nginx/certs/okfn-de-test.matrix.allmende.io/fullchain.pem:/data/okfn-de-test.matrix.allmende.io.crt
      - /srv/nginx/certs/okfn-de-test.matrix.allmende.io/key.pem:/data/okfn-de-test.matrix.allmende.io.key
      - /srv/nginx/certs/dhparam.pem:/data/okfn-de-test.matrix.allmende.io.dhparam.pem
    networks:
      - frontend
      - backend

  data:
    image: "postgres:9.6.3-alpine"
    restart: always
    volumes:
      - /srv/okfn-de-test/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: matrix
      POSTGRES_PASSWORD:
    networks:
      - backend

networks:
  frontend:
    external:
      name: nginx_default
  backend:
    driver: bridge
