version: '2'

services:

  vector:
    image: allmende/vector:0.7.3
    command: start
    environment:
      VIRTUAL_HOST: vector.allmende.io
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: vector.allmende.io
      LETSENCRYPT_EMAIL: almeryda@allmende.io
    expose:
      - "8080"
    volumes:
      - /srv/matrix/allmende:/data

  matrix:
    image: allmende/synapse:0.16.1
    command: start
    environment:
      VIRTUAL_HOST: matrix.allmende.io
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: matrix.allmende.io
      LETSENCRYPT_EMAIL: almereyda@allmende.io
    expose:
      - "8080"
    volumes:
      - /srv/matrix/allmende:/data

  coturn:
    image: allmende/coturn
    command: start
    expose:
      - "3478"
      - "3479"
      - "5349"
      - "5350"
    ports:
      - "3478:3478/udp"
    volumes:
      - /srv/matrix/allmende:/data

networks:
  default:
    external:
      name: nginx_default
