version: '2'

services:

  vector:
    image: allmende/vector:0.7.3
    restart: always
    command: start
    environment:
      VIRTUAL_HOST: vector.allmende.io
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: vector.allmende.io
      LETSENCRYPT_EMAIL: almeryda@allmende.io
    expose:
      - "8080"
    volumes:
      - /srv/matrix/allmende:/data

  matrix:
    image: allmende/synapse:v0.18.7
    restart: always
    command: start
    environment:
      VIRTUAL_HOST: matrix.allmende.io
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: matrix.allmende.io
      LETSENCRYPT_EMAIL: almereyda@allmende.io
    expose:
      - "8080"
    volumes:
      - /srv/matrix/allmende:/data
      - /srv/nginx/certs/matrix.allmende.io/fullchain.pem:/data/matrix.allmende.io.crt
      - /srv/nginx/certs/matrix.allmende.io/key.pem:/data/matrix.allmende.io.key
      - /srv/nginx/certs/dhparam.pem:/data/matrix.allmende.io.dhparam.pem

  coturn:
    image: allmende/coturn
    restart: always
    command: start
    expose:
      - "3478"
      - "3479"
      - "5349"
      - "5350"
    ports:
      - "3478:3478/udp"
    volumes:
      - /srv/matrix/allmende:/data

networks:
  default:
    external:
      name: nginx_default
