version: '2'

services:

  riot:
    image: allmende/riot:20170918
    restart: always
    command: start
    environment:
      VIRTUAL_HOST: riot.allmende.io
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: riot.allmende.io
      LETSENCRYPT_EMAIL: almeryda@allmende.io
    expose:
      - "8080"
    volumes:
      - /srv/matrix/allmende:/data
    logging:
      driver: none
    networks:
      - frontend

  matrix:
    image: allmende/synapse:v0.22.1
    restart: always
    command: start
    environment:
      VIRTUAL_HOST: matrix.allmende.io
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: matrix.allmende.io
      LETSENCRYPT_EMAIL: almereyda@allmende.io
    expose:
      - "8080"
    ports:
      - "8448:8448"
    volumes:
      - /srv/matrix/allmende:/data
      - /srv/nginx/certs/matrix.allmende.io/fullchain.pem:/data/matrix.allmende.io.crt
      - /srv/nginx/certs/matrix.allmende.io/key.pem:/data/matrix.allmende.io.key
      - /srv/nginx/certs/dhparam.pem:/data/matrix.allmende.io.dhparam.pem
    logging:
      driver: none
    networks:
      - frontend
      - backend

  coturn:
    image: allmende/coturn
    restart: always
    command: start
    expose:
      - "3478"
      - "3479"
      - "5349"
      - "5350"
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "3479:3479"
      - "3479:3479/udp"
      - "5349:5349"
      - "5349:5349/udp"
      - "5350:5350"
      - "5350:5350/udp"
#      - "49152-65535:49152-65535/udp"
    volumes:
      - /srv/matrix/allmende:/data

  data:
    image: "postgres:9.6.3-alpine"
    restart: always
    volumes:
      - /srv/matrix/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: matrix
      POSTGRES_PASSWORD:
    networks:
      - backend

networks:
  frontend:
    external:
      name: nginx_default
  backend:
    driver: bridge
