version: '2'

services:

  riot:
    image: allmende/riot:20170918
    command: start
    environment:
      VIRTUAL_HOST: riot.allmende.io
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: riot.allmende.io
      LETSENCRYPT_EMAIL: almeryda@allmende.io
    expose:
      - "8080"
    volumes:
      - /data/domains/matrix.allmende.io/allmende:/data
    logging:
      driver: none
    networks:
      - frontend-web

  matrix:
    image: allmende/synapse:v0.25.1
    command: start
    environment:
      VIRTUAL_HOST: matrix.allmende.io
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: matrix.allmende.io
      LETSENCRYPT_EMAIL: almereyda@allmende.io
    expose:
      - "8080"
    ports:
      - "8448:8448"
    volumes:
      - /data/domains/matrix.allmende.io/allmende:/data
    logging:
      driver: none
    networks:
      - frontend-web
      - backend

  coturn:
    image: allmende/coturn
    command: start
    expose:
      - "3478"
      - "3479"
      - "5349"
      - "5350"
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "3479:3479"
      - "3479:3479/udp"
      - "5349:5349"
      - "5349:5349/udp"
      - "5350:5350"
      - "5350:5350/udp"
#      - "49152-65535:49152-65535/udp"
    volumes:
      - /data/domains/matrix.allmende.io/allmende:/data
    logging:
      driver: none

  data:
    image: "postgres:9.6.3-alpine"
    volumes:
      - /data/bases/matrix.allmende.io/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: matrix
      POSTGRES_PASSWORD:
    networks:
      - backend
    logging:
      driver: none

networks:
  frontend-web:
    external: true
  backend:
    driver: bridge
