version: '2'

services:

  vector:
    image: allmende/vector
    command: generate
    volumes:
      - /srv/matrix/example:/data
    environment:
      - SERVER_NAME=matrix.allmende.io

  matrix:
    image: allmende/synapse
    command: generate
    volumes:
      - /srv/matrix/example:/data
    environment:
      - REPORT_STATS=yes
      - SERVER_NAME=matrix.allmende.io
    depends_on:
      - coturn

  coturn:
    image: allmende/coturn
    command: generate
    volumes:
      - /srv/matrix/example:/data
    environment:
      - SERVER_NAME=matrix.allmende.io
