version: '2'

services:
  matrix:
    build:
      context: ./images/matrix/
    command: generate
    volumes:
      - /srv/matrix/example:/data
    environment:
      - SERVER_NAME=matrix.allmende.io
      - REPORT_STATS=yes
  coturn:
    build:
      context: ./images/coturn/
    command: generate
    volumes:
      - /srv/matrix/example:/data
    environment:
      - SERVER_NAME=matrix.allmende.io
