version: '2'

services:

  matrix:
    image: allmende/synapse:v0.21.1
    command: generate
    volumes:
      - /srv/okfn-de-test/data:/data
    environment:
      - REPORT_STATS=yes
      - SERVER_NAME=okfn-de-test.matrix.allmende.io
